using Bogus;
using Cruxa.Domain.Enums;

namespace Cruxa.Tests;

/// <summary>
/// Pure AutoBogus test data generator.
/// Types without an override are auto-generated by AutoBogus.
/// </summary>
public sealed class TestFixture
{
    private readonly IAutoFaker _faker;

    public TestFixture()
    {
        Faker = new Faker("ru");
        _faker = AutoFaker.Create(builder =>
        {
            builder.WithLocale("ru");
            builder.WithOverride(new RegisterCommandOverride());
            builder.WithOverride(new CreateGymCommandOverride());
            builder.WithOverride(new CreateRouteCommandOverride());
            builder.WithOverride(new AddRouteReviewCommandOverride());
            builder.WithOverride(new UpdateRouteReviewCommandOverride());
        });
    }
    
    public Faker Faker { get; }

    public T Create<T>() => _faker.Generate<T>();
    public List<T> CreateMany<T>(int count) => _faker.Generate<T>(count);

    // ---- AutoGeneratorOverrides ----
    // Конструируем record целиком — Preinitialize=true с positional records
    // несовместим (context.Instance = null), а with { } на null не работает.

    private sealed class RegisterCommandOverride : AutoGeneratorOverride
    {
        public override bool CanOverride(AutoGenerateContext context) =>
            context.GenerateType == typeof(RegisterCommand);

        public override void Generate(AutoGenerateOverrideContext context)
        {
            var person = context.Faker.Person;
            context.Instance = new RegisterCommand(
                Username: person.UserName,
                Email: person.Email.ToLowerInvariant(),
                Password: context.Faker.Internet.Password(),
                City: person.Address.City
            );
        }
    } 

    private sealed class CreateGymCommandOverride : AutoGeneratorOverride
    {
        public override bool CanOverride(AutoGenerateContext context) =>
            context.GenerateType == typeof(CreateGymCommand);

        public override void Generate(AutoGenerateOverrideContext context)
        {
            context.Instance = new CreateGymCommand(
                Name: context.Faker.Company.CompanyName(),
                City: context.Faker.Address.City(),
                Address: context.Faker.Address.StreetAddress(),
                Latitude: context.Faker.Address.Latitude(),
                Longitude: context.Faker.Address.Longitude(),
                Description: context.Faker.Lorem.Sentence(),
                ContactInfo: context.Faker.Phone.PhoneNumber(),
                Website: context.Faker.Internet.DomainName(),
                WorkingHours: """{"Mon":"8:00-23:00"}"""
            );
        }
    }

    private sealed class CreateRouteCommandOverride : AutoGeneratorOverride
    {
        public override bool CanOverride(AutoGenerateContext context) =>
            context.GenerateType == typeof(CreateRouteCommand);

        public override void Generate(AutoGenerateOverrideContext context)
        {
            context.Instance = new CreateRouteCommand(
                GymId: Guid.NewGuid(),
                GradeRaw: context.Faker.PickRandom(
                    "4a", "4b", "4c", "5a", "5b", "5c",
                    "6a", "6b", "6c", "7a", "7b", "7c", "8a"),
                Type: context.Faker.PickRandom<RouteType>(),
                HoldColor: context.Faker.PickRandom<HoldColor>(),
                Sector: context.Faker.Lorem.Word()
            );
        }
    }

    private sealed class AddRouteReviewCommandOverride : AutoGeneratorOverride
    {
        public override bool CanOverride(AutoGenerateContext context) =>
            context.GenerateType == typeof(AddRouteReviewCommand);

        public override void Generate(AutoGenerateOverrideContext context)
        {
            context.Instance = new AddRouteReviewCommand(
                RouteId: Guid.NewGuid(),
                UserId: Guid.NewGuid(),
                Rating: context.Faker.Random.Int(1, 5),
                PrivateNotes: context.Faker.Lorem.Sentence(),
                PublicReview: context.Faker.Lorem.Sentence()
            );
        }
    }

    private sealed class UpdateRouteReviewCommandOverride : AutoGeneratorOverride
    {
        public override bool CanOverride(AutoGenerateContext context) =>
            context.GenerateType == typeof(UpdateRouteReviewCommand);

        public override void Generate(AutoGenerateOverrideContext context)
        {
            context.Instance = new UpdateRouteReviewCommand(
                Id: Guid.NewGuid(),
                UserId: Guid.NewGuid(),
                Rating: context.Faker.Random.Int(1, 5),
                PrivateNotes: context.Faker.Lorem.Sentence(),
                PublicReview: context.Faker.Lorem.Sentence()
            );
        }
    }
}
